# -------------------------------
# Run PyLint for src/
# Run Flake8 for tests/
# -------------------------------

name: OnPush-Linters-PyLint-Flake8

on:
  push:
    branches:
      - main

jobs:
  run_pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code (git clone)
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip and install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run pylint for src folder
      run: pylint src/

  run_flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout code (git clone)
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Update pip and install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run flake8 for tests folder
      run: flake8 tests/
